---
- name: move service script
  command: cp "/opt/winstore/etc/rc.d/init.d/{{item}}" /etc/init.d
  with_items:
    - carbon
    - diamond
    - winstore-httpd
    - winstore-agent
    - winstore-initialize
    - winstore-operation
    - winstore-db
    - winstore-master

- name: make sure service script excutable
  command: chmod a+x "/etc/init.d/{{item}}"
  with_items:
    - carbon
    - diamond
    - winstore-httpd
    - winstore-agent
    - winstore-initialize
    - winstore-operation
    - winstore-db
    - winstore-master

- name: add service 
  command: chkconfig --add {{item}}  
  with_items:
    - carbon
    - diamond
    - winstore-httpd
    - winstore-agent
    - winstore-initialize
    - winstore-operation
    - winstore-db

- name: service on
  command: chkconfig  {{item}} on 
  with_items:
    - carbon
    - diamond
    - winstore-httpd
    - winstore-agent
    - winstore-initialize
    - winstore-operation
    - winstore-db

- name: systemctl enable
  command: systemctl enable {{item}}.service
  with_items:
    - tgtd

- name: systemctl mask ntpd
  command: systemctl disable {{item}}.service
  with_items:
    - ntpd

