--- 
- name: change owner to sdsadmin
  file: path="{{item}}" owner=sdsadmin group=sdsadmin recurse=yes
  with_items:
    - /opt/winstore


- name: last remove the install resource
  file: path="{{item}}" state=absent
  with_items:
    - /root/install_rpms
    - /root/install_venv
    - /root/winstore
    - /root/install_ceph_rpms
    - /root/install_more_rpms
    - /root/install_tgt
    - /root/install_cairo
    - /root/nvme-cli
    - /root/virtualenv
    - /root/install_mysql_rpms

## at last we reboot the machine 
  
- name: reboot
  shell: reboot
  ignore_errors: yes
