---

- name: unarchive install_rpms
  unarchive:
    src: "resource/install_rpms.tar.gz"
    dest: /root

- name: remove perl-Filter
  file: path="/root/install_rpms/perl-Filter-1.49-3.el7.x86_64.rpm" state=absent
  ignore_errors: True
  when: winserver is defined

- name: remove old openssl openssl-devel
  shell: yum remove -y openssl-devel openssl
  ignore_errors: True
  when: winserver is defined

- name: install libselinux-python,rsync,gcc,perl,python-devel
  shell: yum localinstall -yC --disablerepo=* `ls /root/install_rpms/*.rpm`

- name: unarchive nvme-cli
  unarchive:
    src: "resource/others/nvme-cli.tar.gz"
    dest: /root

- name: install nvme-cli
  shell: cd /root/nvme-cli && make && make install
  ignore_errors: True

- name: upload ssh key
  authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ansible_connection != "local"
