---
  
- name: unarchive ceph rpms
  unarchive:
    src: "resource/install_ceph_rpms.tar.gz"
    dest: /root
    
- name: install ceph rpms
  shell: yum localinstall -yC --disablerepo=* /root/install_ceph_rpms/*.rpm

#- name: ceph service on
#  command: chkconfig ceph on
