---
  
- name: unarchive mysql rpms
  unarchive:
    src: "resource/install_mysql_rpms.tar.gz"
    dest: /root
  when: db_install is defined

- name: install mysql rpms
  shell: yum localinstall -yC --disablerepo=* /root/install_mysql_rpms/*.rpm
  when: db_install is defined

- name: mysqld service on
  shell: systemctl enable mysqld
  when: db_install is defined

- name: mysqld service start
  shell: systemctl start mysqld
  ignore_errors: yes
  when: db_install is defined

- name: change root password
  shell: sh /root/winstore-ansible/resource/shell/mysql.sh {{mysql_password}}
  ignore_errors: yes
  when: db_install is defined

- name: mysqld service restart
  shell: systemctl restart mysqld
  when: db_install is defined

