---

- name: unarchive download_pip
  unarchive:
    src: "resource/install_venv.tar.gz"
    dest: /root

# 安装venv环境
- name: install setuptools|pip|virtualenv
  shell: sh /root/winstore-ansible/resource/shell/venv.sh

- name: install cffi
  pip:
    name: cffi
    virtualenv: /opt/winstore/venv
    virtualenv_python: "{{python_version}}"
    extra_args: '--no-index --find-links file:///root/install_venv'

- name: install requirements
  pip:
    requirements: /root/install_venv/requirements.txt
    virtualenv: /opt/winstore/venv
    virtualenv_python: "{{python_version}}"
    extra_args: '--no-index --find-links file:///root/install_venv'

# 安装 carbon
- name: install carbon
  pip:
    name: carbon
    virtualenv: /opt/winstore/venv
    virtualenv_python: "{{python_version}}"
    extra_args: '--no-index --find-links file:///root/install_venv
      --install-option="--prefix=/opt/winstore/venv"
      --install-option="--install-lib=/opt/winstore/venv/lib/{{python_version}}/site-packages"'

# 安装 graphite-web
- name: install graphite-web
  pip:
    name: graphite-web
    virtualenv: /opt/winstore/venv
    virtualenv_python: "{{python_version}}"
    extra_args: '--no-index --find-links file:///root/install_venv
      --install-option="--prefix=/opt/winstore/venv"
      --install-option="--install-lib=/opt/winstore/venv/lib/{{python_version}}/site-packages"'

# 启用系统python模块
- name: remove no-global-site-packages.txt
  file: path="/opt/winstore/venv/lib/{{python_version}}/no-global-site-packages.txt" state=absent

- name: last remove the folder /root/setuptools /root/pip
  file: path="{{item}}" state=absent
  with_items:
    - /root/setuptools
    - /root/pip

