---

- name: 安装基础软件
  hosts: all
  remote_user: root
  roles:
    - {role: common, tags: ['common']}
    - {role: more-rpms, tags: ['more-rpms']}


- name: 安装mysql
  hosts: localhost
  roles:
    - {role: mysql, tags: ['mysql']}


- name: ansible必要参数debug
  hosts: all
  remote_user: root
  roles:
    - {role: debug, tags: ['debug']}


- name: 安装前必须优先做的配置工作
  hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - {role: prepare, tags: ['pre-config']}


- name: 安装winstore python 虚拟环境部分
  hosts: all
  remote_user: root
  roles:
    - {role: venv, tags: ['venv']}


- name: 安装ceph
  hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - {role: ceph, tags:  ['ceph']}


- name: 安装tgt
  hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - {role: tgt, tags: ['tgt']}


- name: 安装winstore apache 部分
  hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - {role: apache, tags: ['apache']}


- name: 安装winstore 骨架部分，配置部分后续处理
  hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - {role: winstore, tags: ['winstore']}


- name: 更新winstore源码
  hosts: all
  remote_user: root
  gather_facts: False
  roles:
    - {role: update-winstore, tags:  ['update-winstore']}


- name: 后配置部分
  hosts: all
  remote_user: root
  roles:
    - {role: config-winstore, tags: ['config-winstore', 'config']}
    - {role: config-apache, tags: ['config-apache','config']} 
    - {role: config-service, tags: ['config-service','config']}
    - {role: config-patch, tags: ['config-patch', 'config']}  
    - {role: config-others, tags: ['config-others','config']}       
